on: [push, workflow_dispatch]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name:  Build with Jenny
    steps:
    - uses: actions/checkout@v2
    - name: Build to .dist
      uses: hmngwy/jenny@master
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: .dist
