on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build with jenny 
    steps:
    - uses: actions/checkout@v2
    - name: build to .dist
      id: jenny
      uses: hmngwy/blog/.github/actions/jenny@master
